# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .pipeline import *
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_concourse.config as config
else:
    config = _utilities.lazy_import('pulumi_concourse.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "concourse",
  "mod": "index",
  "fqn": "pulumi_concourse",
  "classes": {
   "concourse:index:Pipeline": "Pipeline"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "concourse",
  "token": "pulumi:providers:concourse",
  "fqn": "pulumi_concourse",
  "class": "Provider"
 }
]
"""
)
