// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class AnonymousResourceArgs : Pulumi.ResourceArgs
    {
        [Input("params")]
        private InputMap<string>? _params;
        public InputMap<string> Params
        {
            get => _params ?? (_params = new InputMap<string>());
            set => _params = value;
        }

        [Input("source", required: true)]
        private InputMap<string>? _source;
        public InputMap<string> Source
        {
            get => _source ?? (_source = new InputMap<string>());
            set => _source = value;
        }

        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public AnonymousResourceArgs()
        {
        }
    }
}
