// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class DisplayOptionsArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allows users to specify a custom background image which is put at 30% opacity, grayscaled and blended into existing background. Must be an http, https, or relative URL.
        /// </summary>
        [Input("backgroundImage")]
        public Input<string>? BackgroundImage { get; set; }

        public DisplayOptionsArgs()
        {
        }
    }
}
