// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class GetStepArgs : Pulumi.ResourceArgs
    {
        [Input("get", required: true)]
        public Input<string> Get { get; set; } = null!;

        [Input("params")]
        private InputMap<string>? _params;
        public InputMap<string> Params
        {
            get => _params ?? (_params = new InputMap<string>());
            set => _params = value;
        }

        [Input("passed")]
        private InputList<string>? _passed;
        public InputList<string> Passed
        {
            get => _passed ?? (_passed = new InputList<string>());
            set => _passed = value;
        }

        [Input("resource")]
        public Input<string>? Resource { get; set; }

        [Input("trigger")]
        public Input<bool>? Trigger { get; set; }

        public GetStepArgs()
        {
        }
    }
}
