// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class GroupArgs : Pulumi.ResourceArgs
    {
        [Input("jobs")]
        private InputList<string>? _jobs;

        /// <summary>
        /// A list of jobs that should appear in this group. A job may appear in multiple groups. Neighbours of jobs in the current group will also appear on the same page in order to give context of the location of the group in the pipeline. You may also use any valid glob to represent several jobs.
        /// </summary>
        public InputList<string> Jobs
        {
            get => _jobs ?? (_jobs = new InputList<string>());
            set => _jobs = value;
        }

        /// <summary>
        /// A unique name for the group. This should be short and simple as it will be used as the tab name for navigation.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GroupArgs()
        {
        }
    }
}
