// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class InParallelStepArgs : Pulumi.ResourceArgs
    {
        [Input("in_parallel", required: true)]
        public Input<Inputs.InParallelConfigArgs> In_parallel { get; set; } = null!;

        public InParallelStepArgs()
        {
        }
    }
}
