// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class TaskStepArgs : Pulumi.ResourceArgs
    {
        [Input("config")]
        public Input<Inputs.TaskConfigArgs>? Config { get; set; }

        [Input("image")]
        public Input<string>? Image { get; set; }

        [Input("task", required: true)]
        public Input<string> Task { get; set; } = null!;

        public TaskStepArgs()
        {
        }
    }
}
