// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Concourse.Inputs
{

    public sealed class TaskConfigArgs : Pulumi.ResourceArgs
    {
        [Input("image_resource", required: true)]
        public Input<Inputs.AnonymousResourceArgs> Image_resource { get; set; } = null!;

        [Input("platform", required: true)]
        public Input<string> Platform { get; set; } = null!;

        [Input("run", required: true)]
        public Input<Inputs.RunArgsArgs> Run { get; set; } = null!;

        public TaskConfigArgs()
        {
        }
    }
}
