# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

password: Optional[str]
"""
Password for basic auth.
"""

url: Optional[str]
"""
URL of your concourse instance.
"""

username: Optional[str]
"""
Username for basic auth.
"""

