# coding=utf-8
# *** WARNING: this file was generated by pulumigen. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('concourse')


class _ExportableConfig(types.ModuleType):
    @property
    def password(self) -> Optional[str]:
        """
        Password for basic auth.
        """
        return __config__.get('password')

    @property
    def team(self) -> Optional[str]:
        """
        Team to authenticate with.
        """
        return __config__.get('team')

    @property
    def url(self) -> Optional[str]:
        """
        URL of your concourse instance.
        """
        return __config__.get('url')

    @property
    def username(self) -> Optional[str]:
        """
        Username for basic auth.
        """
        return __config__.get('username')

