// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

// Password for basic auth.
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "concourse:password")
}

// Team to authenticate with.
func GetTeam(ctx *pulumi.Context) string {
	return config.Get(ctx, "concourse:team")
}

// URL of your concourse instance.
func GetUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "concourse:url")
}

// Username for basic auth.
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "concourse:username")
}
